### ISSUE TITLE
Sequence contains no matching element by using custom ONNX File

### ISSUE THREAD

**Issue by zimmym** [mentalstack/yolov5-net#13]
Hi, by trying to use a custom Onnx File there is an exception:

System.InvalidOperationException
    Nachricht = Sequence contains no matching element
  Quelle = System.Linq

_line 130, YoloScorer.cs_

Source Code:

  private DenseTensor<float>[] Inference(Image image)
    {
            Bitmap resized = null;

            if (image.Width != _model.Width || image.Height != _model.Height)
            {
                resized = ResizeImage(image); // fit image size to specified input size
            }

            var inputs = new List<NamedOnnxValue> // add image as onnx input
            {
                NamedOnnxValue.CreateFromTensor("image_tensor", ExtractPixels(resized ?? image))
            };

            var result = _inferenceSession.Run(inputs); // run inference session

            var output = new List<DenseTensor<float>>();

            foreach (var item in _model.Outputs) // add outputs for processing
            {
                               **_// HERE THE EXCEPTION OCCUR_**
               output.Add(result.Last(x => x.Name == item).Value as DenseTensor<float>);
            };

            return output.ToArray();
        }

**Comment by kkarahainko** [comment]
@zimmym inspect your onnx with Netron and check output names, looks like model config Outputs and onnx outputs are not the same.
