### ISSUE TITLE
onnx export file using image width:640 and height:640 not detecting any predictions

### ISSUE THREAD

**Issue by alijundi** [mentalstack/yolov5-net#15]
@kkarahainko 

First of all I would like to thank you for this awesome library. I now started training my custom model and was able to detect everything as expected using python detect.py

I export the .pt file of my model using the below command:
`python export.py --weights custom_dataset/ReadyModel/SMDB.pt --img 640 --batch 1`

Then I used that in the asset and made my custom model baed on the YoloCocoP5.cs model. I only changed the Labels to match my model.

I noticed that there is no predictions coming out when testing the same image in python which gave an amazing result. I am confident there is something I am missing here in C# wrapper. Can you point me to the correct direction? 

Thanks alot!

**Comment by kkarahainko** [comment]
@alijundi hi, can you pls provide .pt & .onnx files and a test image? I'll check on my side.

**Comment by kkarahainko** [comment]
@alijundi and model config as well.

**Comment by alijundi** [comment]
@kkarahainko I actually changed the depth from 85 to 9 and looks like it is working now! But the prediction confidence is very different than what I am getting in python. Please see the result from the too.

RESULT FROM python:
![66](https://user-images.githubusercontent.com/4628726/132641416-0368b01c-7a67-4ff9-9639-bc3a79fc896f.jpg)
RESULT FROM Wrapper:
![result](https://user-images.githubusercontent.com/4628726/132641495-04b64a85-cc12-441a-ad6b-6820d1f8e440.jpg)

MY MODEL CODE NOW:

```
public class SMDBModel : YoloModel
    {
        public override int Width { get; set; } = 640;
        public override int Height { get; set; } = 640;
        public override int Depth { get; set; } = 3;

        public override int Dimensions { get; set; } = 9;

        public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

        public override float[][][] Anchors { get; set; } = new float[][][]
        {
            new float[][] { new float[] { 010, 13 }, new float[] { 016, 030 }, new float[] { 033, 023 } },
            new float[][] { new float[] { 030, 61 }, new float[] { 062, 045 }, new float[] { 059, 119 } },
            new float[][] { new float[] { 116, 90 }, new float[] { 156, 198 }, new float[] { 373, 326 } }
        };

        public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

        public override float Confidence { get; set; } = 0.20f;
        public override float MulConfidence { get; set; } = 0.25f;
        public override float Overlap { get; set; } = 0.45f;

        public override string[] Outputs { get; set; } = new[] { "output" };

        public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
        {
            new YoloLabel { Id = 1, Name = "MCCB_3P"},
            new YoloLabel { Id = 2, Name = "PANEL_DETAILS" },
            new YoloLabel { Id = 3, Name = "PANEL" },
            new YoloLabel { Id = 4, Name = "MCCB_1P" }
        };

        public override bool UseDetect { get; set; } = true;

        public SMDBModel()
        {

        }
    }
```
Download link for model .pt and .onnx:
[https://we.tl/t-Bm0mte4TQA]

If you need any more information please let me know.

Thank you.

**Comment by alijundi** [comment]
@kkarahainko I forgot to include the test image. Here you go:

![test66](https://user-images.githubusercontent.com/4628726/132648583-2a91b190-25d3-4215-ab19-e5be52584f1c.jpg)

**Comment by alijundi** [comment]
@kkarahainko did you happen to test it already? I have spent hours and until now I have no clue why this is happening!

**Comment by kkarahainko** [comment]
@alijundi yes, i found the problem, do you use nuget package or cloned locally? Going to push changes in next few hours.

**Comment by alijundi** [comment]
@kkarahainko I cloned it locally.

Once uploaded if you can explain what was the issue that would be great.

**Comment by kkarahainko** [comment]
@alijundi pushed. pls try, image resizing method (to fit model input size) was not correct, now it keeps ratio.

**Comment by alijundi** [comment]
@kkarahainko Excellent work!

Now it woks perfectly fine. Thank you so much.

I will close issue now.
