### ISSUE TITLE
hi can  make a demo video?

### ISSUE THREAD

**Issue by pandyer** [mentalstack/yolov5-net#16]
I remade onNX but don't know how to modify YoloModel.

**Comment by kkarahainko** [comment]
@pandyer 

1. inspect your model with Netron app (input: images), https://i.imgur.com/DxohNvC.png;
2. inherit your custom model class from YoloModel, change Width, Height, Dimensions (labels count + 5) then add your Labels, change Outputs (from Netron) if required;
3. use this https://github.com/mentalstack/yolov5-net/blob/master/src/Yolov5Net.Scorer/Models/YoloCocoP5Model.cs for reference.
