### ISSUE TITLE
Add images to my model during runtime and retrain

### ISSUE THREAD

**Issue by alijundi** [mentalstack/yolov5-net#18]
Hi @kkarahainko

In my case I need the user to add labeled images to the trained model while in runtime. It is some some sort of feedback to the system.

Is it possible to do here? Or it is just via Python and retrain using existing weights and adding the images to the dataset then export to onnx.

It would be great if we can do it in c# since the added images are single items that will add accuracy to the model in the future uses.

I appreciate your insight on the topic.

**Comment by kkarahainko** [comment]
@alijundi not possible... you have to retrain https://github.com/ultralytics/yolov5/issues/980, https://github.com/ultralytics/yolov5/issues/1071.
