### ISSUE TITLE
custom model doesn't work even I changed the dimension and shape

### ISSUE THREAD

**Issue by jacklee-code** [mentalstack/yolov5-net#22]
the .onnx and .pt work both in yolov5 detect.py but I don't know why the .onnx doesn't work on Yolov5-Net.
I believe that Yolov5-Net is functioning well since the result is fine if I change the model and weight to YoloCocoP5Model and yolov5s.onnx. It just doesn't work if I use my own model. Here is my code :

class HarryPotterModel : YoloModel
    {
        public override int Width { get; set; } = 640;
        public override int Height { get; set; } = 640;
        public override int Depth { get; set; } = 3;

        public override int Dimensions { get; set; } = 6;

        public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

        public override float[][][] Anchors { get; set; } = new float[][][]
        {
            new float[][] { new float[] { 010, 13 }, new float[] { 016, 030 }, new float[] { 033, 023 } },
            new float[][] { new float[] { 030, 61 }, new float[] { 062, 045 }, new float[] { 059, 119 } },
            new float[][] { new float[] { 116, 90 }, new float[] { 156, 198 }, new float[] { 373, 326 } }
        };

        public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

        public override float Confidence { get; set; } = 0.20f;
        public override float MulConfidence { get; set; } = 0.25f;
        public override float Overlap { get; set; } = 0.45f;

        public override string[] Outputs { get; set; } = new[] { "output" };

        public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
        {
            new YoloLabel { Id = 1, Name = "player" },         
        };

        public override bool UseDetect { get; set; } = true;

        public HarryPotterModel()
        {

        }
    }
.onnx file download link: https://drive.google.com/file/d/1w4HssuY7mOYvn7G-mUj66KM21PPY8f7B/view?usp=sharing
.pt file download link: https://drive.google.com/file/d/1SpgqWcx90nTt9GqWsnaYF8yYrimUSUch/view?usp=sharing

test image
![test](https://user-images.githubusercontent.com/81527133/135953667-ca652c5b-ab68-43f8-8b09-103d5f3b59da.jpg)

result in detect.py (using .onnx not .pt)
![reuslt](https://user-images.githubusercontent.com/81527133/135953773-e6182167-4bdd-4eaf-9a20-ad839837fef7.jpg)

Thank you for your help.

**Comment by dstampher** [comment]
@jacklee-code I noticed that your output from detect.py has the bounding box labeled as "class0", but in YoloV5-Net you have the class name "person", not sure if that will matter here but maybe changing "person" to "class0" might work for you.

I also wanted to say that I cloned this repo today and am having the same issue, but also a problem with changing the height/width of a model.  I trained a model to detect crosswalks, using the weights from yolov5s.pt, and also trained at 320x320.  It works great with detect.py, so I converted the weights file to onnx using export.py that is included in the yolov5 repo. When I change the width/height to 320 in my C# class that inherits from YoloModel and run Program.cs, I get the following exception/stack trace

```
Unhandled exception. Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidArgument] Got invalid di
mensions for input: images for the following indices
 index: 2 Got: 320 Expected: 640
 index: 3 Got: 320 Expected: 640
 Please fix either the inputs or the model.
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.RunImpl(RunOptions options, IntPtr[] inputNames, IntPtr[] inpu
tValues, IntPtr[] outputNames, DisposableList`1 cleanupList)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs, IReadOnlyCollection`1 output
Names, RunOptions options)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs, IReadOnlyCollection`1 output
Names)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Run(IReadOnlyCollection`1 inputs)
   at Yolov5Net.Scorer.YoloScorer`1.Inference(Image image) in C:\Users\david\repos\yolov5-net\src\Yolov5Net.Sc
orer\YoloScorer.cs:line 131
   at Yolov5Net.Scorer.YoloScorer`1.Predict(Image image) in C:\Users\david\repos\yolov5-net\src\Yolov5Net.Scor
er\YoloScorer.cs:line 310
   at Yolov5Net.App.Program.Main(String[] args) in C:\Users\david\repos\yolov5-net\src\Yolov5Net.App\Program.c
s:line 17

Process finished with exit code -532,462,766.

```

And here is my class:

```
public class YoloRecaptchaModel : YoloModel
{
    public override int Width { get; set; } = 640;
    public override int Height { get; set; } = 640;
    public override int Depth { get; set; } = 3;

    public override int Dimensions { get; set; } = 85;

    public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

    public override float[][][] Anchors { get; set; } = new float[][][]
    {
        new float[][] { new float[] { 010, 13 }, new float[] { 016, 030 }, new float[] { 033, 023 } },
        new float[][] { new float[] { 030, 61 }, new float[] { 062, 045 }, new float[] { 059, 119 } },
        new float[][] { new float[] { 116, 90 }, new float[] { 156, 198 }, new float[] { 373, 326 } }
    };

    public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

    public override float Confidence { get; set; } = 0.20f;
    public override float MulConfidence { get; set; } = 0.25f;
    public override float Overlap { get; set; } = 0.45f;

    public override string[] Outputs { get; set; } = new[] { "output" };

    public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
    {
        new YoloLabel { Id = 1, Name = "crosswalks" },
    };

    public override bool UseDetect { get; set; } = true;

    public YoloRecaptchaModel()
    {

    }
}
```

I am retraining my model at 640x640 now, hopefully it will detect the crosswalks when I test it with this repo.

**Comment by jacklee-code** [comment]
@dstampher yes, I have noticed that export.py change my label from 'player' to 'class0'. I have tried both new YoloLabel { Id = 1, Name = "player" } and new YoloLabel { Id = 1, Name = "class0" }. They all not working for me I don't know why. :(

**Comment by dstampher** [comment]
@jacklee-code Yeah same here, I just tried that for my own use case and it still didn't work unfortunately.  I am wondering if maybe some of the properties that we are using are invalid for our models.  If you were like me, you copied one of the included classes and just changed the labels.  

I am doing some experimenting right now, but hopefully one of the contributors of this repo can jump in here.

**Comment by kkarahainko** [comment]
@jacklee-code thanks for it, found an issue, changes pushed @dstampher if you trained on 320 then change you w,h to 320 in model config (C# class).

**Comment by kkarahainko** [comment]
@dstampher please open a new issue and provide me with onnx file and test image, just to not mix with @jacklee-code's issue, hard to answer.

**Comment by jacklee-code** [comment]
@kkarahainko there still no prediction after I clone the lastest source code into my project

**Comment by kkarahainko** [comment]
@jacklee-code 

inference:

```
using var image = Image.FromFile("Assets/harry.jpg");
using var scorer = new YoloScorer<HarryModel>("Assets/Weights/best.onnx");
List<YoloPrediction> predictions = scorer.Predict(image);

```

model config:

```
public class HarryModel : YoloModel
    {
        public override int Width { get; set; } = 640;
        public override int Height { get; set; } = 640;
        public override int Depth { get; set; } = 3;

        public override int Dimensions { get; set; } = 6;

        public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

        public override float[][][] Anchors { get; set; } = new float[][][]
        {
            new float[][] { new float[] { 010, 13 }, new float[] { 016, 030 }, new float[] { 033, 023 } },
            new float[][] { new float[] { 030, 61 }, new float[] { 062, 045 }, new float[] { 059, 119 } },
            new float[][] { new float[] { 116, 90 }, new float[] { 156, 198 }, new float[] { 373, 326 } }
        };

        public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

        public override float Confidence { get; set; } = 0.20f;
        public override float MulConfidence { get; set; } = 0.25f;
        public override float Overlap { get; set; } = 0.45f;

        public override string[] Outputs { get; set; } = new[] { "output" };

        public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
        {
            new YoloLabel { Id = 0, Name = "player" }
        };

        public override bool UseDetect { get; set; } = true;

        public HarryModel()
        {

        }
    }
```

result:


![result](https://user-images.githubusercontent.com/1279307/135977239-a53981f5-a786-4173-8a49-16a880e726d4.jpg)

**Comment by jacklee-code** [comment]
@kkarahainko thank you very much. It's my fault. I forgot to change "new YoloScorer<MODEL_CLASS>" to my own model after the test. Thank you very much!!
