### ISSUE TITLE
Difference between Confidence and MulConfidence attributes?

### ISSUE THREAD

**Issue by Tomdri** [mentalstack/yolov5-net#23]
I don't quite understand the difference between the two model parameters. Which one is the actual confidence threshold where predictions lower than the threshold will be rejected ? Do they both have to be set to the same value ?

**Comment by kkarahainko** [comment]
Confidence is responsible for "objectness" - a measure of the probability that an object exists in a proposed region (cell). MullConfidence is the final one, it's what you see as a result = objectness * label confidence (what exact object). So having the ability to control both of them allows you to have better results by tuning these parameters. You may leave Confidence as it is, change only MulConfidence.
