### ISSUE TITLE
Unable to detect object in C# but able to detect in Python

### ISSUE THREAD

**Issue by jacklee-code** [mentalstack/yolov5-net#25]
I write the following code to grab the image of my screen and put it into scorer.Predict(image). Most of the time it detects in the wrong area or it just gets no prediction.

```
private static Bitmap CaptureScreen()
        {
            Bitmap bm = new Bitmap(Screen.PrimaryScreen.Bounds.Width, Screen.PrimaryScreen.Bounds.Height);
            Graphics g = Graphics.FromImage(bm);
            g.CopyFromScreen(0, 0, 0, 0, bm.Size);
            return bm;
        }

```
So I try to save the screenshot from CaptureScreen() and use Image.FromFile to check whether it gets prediction or not. It turns out that it didn't get any prediction. However, I got the correct result if I use detect.py.
I use the following code to load the screenshot into the prediction method:                        
`List<YoloPrediction> predictions = scorer.Predict(CaptureScreen());`

The image that C# doesn't get any prediction but detect.py does (the yellow box is not the prediction):
![cs2](https://user-images.githubusercontent.com/81527133/135994303-3bc6ce9b-0c34-45c0-b7b3-daf78c2768f4.jpg)
detect.py shown below (the yellow box is not the prediction)
![py2](https://user-images.githubusercontent.com/81527133/135994318-c24c9662-7eb5-408e-8785-55ea0599dca0.jpg)

The image that C# and detect.py work both

- **But the weird thing is that if I use Windows Photo to open it and set it to fullscreen, it cannot detect the 'player' by ScreenCapture(). (But it can detect the 'player' if I use Image.FromFile())**

![test](https://user-images.githubusercontent.com/81527133/135994461-bfb3176c-9a03-412d-b90c-3731c5aa2424.jpg)
![result](https://user-images.githubusercontent.com/81527133/135994484-21a8c983-e44d-49e0-a459-82e75d6634ec.jpg)

.onnx file download link: https://drive.google.com/file/d/1w4HssuY7mOYvn7G-mUj66KM21PPY8f7B/view?usp=sharing

**Comment by dstampher** [comment]
Having the same problem over here.  I am getting predictions when I clone the repo, but when I install the latest version v1.0.5 via NuGet, in my own project, I am not getting predictions.  

```
using System;
using System.Drawing;
using Yolov5Net.Scorer;
using Yolov5Net.Scorer.Models;

namespace Example
{
    class Program
    {
        static void Main(string[] args)
        {
            var img = Image.FromFile(@"c:\users\david\test.png");
            using var scorer = new YoloScorer<YoloCocoP5Model>(@"C:\Users\david\repos\yolo\yolov5\yolov5x.onnx");
            var predictions = scorer.Predict(img); //No predictions
        }
    }
}
```

**Comment by kkarahainko** [comment]
@dstampher @jacklee-code thanks guys, the same thing - all test images I use are 24bpp, your one is 32bpp, so pixel extraction improved to handle both pixel formats - check the latest code in repo, let me know.

**Comment by jacklee-code** [comment]
@kkarahainko yep, I just figure out the problem when I use the debugger and set a breakpoint before predict method. After I use Bitmap bm = new Bitmap(Screen.PrimaryScreen.Bounds.Width, Screen.PrimaryScreen.Bounds.Height, PixelFormat.Format24bppRgb); the problem solved. By the way, thanks a lot

**Comment by kkarahainko** [comment]
@jacklee-code thank you, @dstampher does it work for you now?

**Comment by jacklee-code** [comment]
@kkarahainko I would like to know is there any way to improve the speed of the object detection. Since the latency is quite obvious. the fps is about 3~5. However, I got a quite high speed in detect.py. I already Microsoft.ML.OnnxRuntime.Gpu. Is there any setup in order to enable the GPU?

**Comment by jacklee-code** [comment]
Since the game still runs smoothly, So I guess the application is not inferring at maximum speed?

**Comment by kkarahainko** [comment]
@jacklee-code I'm getting quite the same results in Python and C# on CPU:

https://i.imgur.com/Imvn7ys.png

https://i.imgur.com/uIOTZeg.png

to run it with GPU acceleration you need CUDA to be installed and SessionOptions passed to YoloScorer constructor.

**Comment by jacklee-code** [comment]
thanks, I will try with the following code
`SessionOptions option = SessionOptions.MakeSessionOptionWithCudaProvider(0);`

**Comment by kkarahainko** [comment]
@jacklee-code anyway GPUt will speed up inference, but pixel extraction takes ~100ms and works on CPU, I will try SkiaSharp, EmguCV for this.

**Comment by jacklee-code** [comment]
Thanks, got it.
