### ISSUE TITLE
Using SAHI with yolov5 in large image slicing

### ISSUE THREAD

**Issue by alijundi** [mentalstack/yolov5-net#27]
Hi @kkarahainko I think it would be very useful and awesome if we can port the SAHI library https://github.com/obss/sahi to do image slicing for large images before detection which will make the this library much more useful.

Do you think or have an idea where we can use similar functionality in this library here.

I do appreciate any input you can provide.

Thanks.

**Comment by alijundi** [comment]
@kkarahainko Please see below two images (one is a cropped from the big one or let's say sliced):

![E-701-small](https://user-images.githubusercontent.com/4628726/136650867-d759e7c4-d397-4958-ba80-d6316d4af92c.jpg)

and the big one is:
![E-701](https://user-images.githubusercontent.com/4628726/136650887-9bc467b5-c3ec-4014-ace4-b2fe8a319cba.jpg)

Model .pt file download location:
[https://we.tl/t-g4eayUYZTY]

**Comment by alijundi** [comment]
@kkarahainko while I check what you have said above now I am attempting to use a large Yolo Model (yolov5l). When exported to ONNX it does not detect anything as it was before. I am sure there some parameters that need to be changed in the MODEL file in c#. Can you please point me on how to do that.

Thanks.

**Comment by kkarahainko** [comment]
@alijundi nop, it should work as yolov5s, the same model config.

**Comment by alijundi** [comment]
@kkarahainko Thank you. it is working as yolov5s -- it seems that I copied the wrong file!

I will also try P6 models once I complete a good training on this model

**Comment by kkarahainko** [comment]
@alijundi I've tested on 8k images with P5-P6 large models and it works fine with far/small objects, maybe I'll return to this later.

**Comment by kkarahainko** [comment]
@alijundi I still can't find a solution how to resolve such cases https://i.imgur.com/UzdkK13.jpeg, 3 parts are detected as person, 4th path is not detected for example etc... so I cant provide any stable solution for now.
