### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by orielswisa** [mentalstack/yolov5-net#29]
Hey 👋🏽  
I uninstalled onnxruntime and install onnxruntime.gpu but the program still running on cpu.
Can you tell me what I need to do to run on gpu?

**Comment by AndersEben** [comment]
@kkarahainko i tried to get it to work witch CUDA 11.5 but get the error message

### "[ErrorCode:RuntimeException] D:\a\_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered. ### 

It's not an actual yolov5-net error but maybe you can help me.

**Comment by kkarahainko** [comment]
@AndersEben did you install cudnn?

**Comment by AndersEben** [comment]
@kkarahainko Thanks thats fix the problem.

**Comment by orielswisa** [comment]
@AndersEben I have the same problem.
Which version of cudnn you installed?

**Comment by AndersEben** [comment]
@orielswisa I use cuDNN v8.2.1 (June 7th, 2021), for CUDA 11.x 
but for now there is no time improvement instead of using cpu for me. don't know why.
by image size 1280 x 1280 it needs 900ms

**Comment by kkarahainko** [comment]
@AndersEben first run is slow, next predictions will go much faster, I've got 30+ fps on my rtx 3060.

**Comment by AndersEben** [comment]
@kkarahainko yeah first run is by 1300ms and next predictions will run by ~800-950 ms. cpu runs nearly the same for me. dont know if this caused by my gtx1080 or my poorly trained test model.

**Comment by kkarahainko** [comment]
@AndersEben hmm, i have around 100ms on cpu (Ryzen 9), and 30ms on GPU.

**Comment by AndersEben** [comment]
@kkarahainko 
Ryzen7 1700x
Rtx 1080

.NET Framework 4.7.2
Yolov5Net -Version 1.0.7
Microsoft.ML.OnnxRuntime.Gpu -Version 1.9.0

CustomModel:

        public override int Width { get; set; } = 1280;
        public override int Height { get; set; } = 1280;
        public override int Depth { get; set; } = 3;
        public override int Dimensions { get; set; } = 7;
        public override float[] Strides { get; set; } = new float[] { 8, 16, 32, 64 };
        public override float[][][] Anchors { get; set; } = new float[][][]
        {
            new float[][] { new float[] { 019, 027 }, new float[] { 044, 040 }, new float[] { 038, 094 } },
            new float[][] { new float[] { 096, 068 }, new float[] { 086, 152 }, new float[] { 180, 137 } },
            new float[][] { new float[] { 140, 301 }, new float[] { 303, 264 }, new float[] { 238, 542 } },
            new float[][] { new float[] { 436, 615 }, new float[] { 739, 380 }, new float[] { 925, 792 } }
        };
        public override int[] Shapes { get; set; } = new int[] { 80, 40, 20, 10 };
        public override float Confidence { get; set; } = 0.20f;
        public override float MulConfidence { get; set; } = 0.25f;
        public override float Overlap { get; set; } = 0.45f;

        public override string[] Outputs { get; set; } = new[] { "output" };

        public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
        {
            new YoloLabel { Id = 1, Name = "label1" },
            new YoloLabel { Id = 2, Name = "label2" }
        };

        public override bool UseDetect { get; set; } = true;

The usage of the yolo5net is same as the sample.

**Comment by AlexSim** [comment]
I think this GPU issue is not solved.... 

there is no differences on performance at running between CPU and GPU. Very strange~~~

// GPU
 _scorer = new YoloScorer<YoloCocoP5Model>(@"weights\yolov5s.onnx", SessionOptions.MakeSessionOptionWithCudaProvider(deviceId));

// CPU
_scorer = new YoloScorer<YoloCocoP5Model>(@"weights\yolov5s.onnx");


Do you have any idea? 


Thank  U

**Comment by kkarahainko** [comment]
@AlexSim I don't think it's the issue of yolov5-net, I have CUDA 11.4 installed on RTX 3060 that's recommended CUDA version for this hardware, everything work as expected. Please double check compatibility, then run this simple benchmark:

```
var sw = new Stopwatch();
using var image = Image.FromFile("Assets/test.jpg");
var options = SessionOptions.MakeSessionOptionWithCudaProvider(0);
using var scorer = new YoloScorer<YoloCocoP5Model>("Assets/Weights/yolov5n.onnx", options);
List<long> stats = new List<long>();

for (int i = 0; i < 100; i++)
{
    sw.Restart();
    scorer.Predict(image);
    long fps = 1000 / sw.ElapsedMilliseconds;
    stats.Add(fps);
    Console.WriteLine($"FPS: {fps}");
    sw.Stop();
}

Console.WriteLine($"Max FPS: {stats.Max()}");
Console.WriteLine($"Avg FPS: {stats.Average()}");
Console.WriteLine($"Min FPS: {stats.Min()}");

Console.ReadKey();
```

My scores on GPU: 

Max FPS: 38
Avg FPS: 30.62
Min FPS: 0

And on CPU (Ryzen 9, 16 threads):

Max FPS: 22
Avg FPS: 18.76
Min FPS: 9

**Comment by AndersEben** [comment]
I also think its not an yolov5-net issue.

Ryzen7 1700x
Rtx 1080


@kkarahainko  i run your code these are my results:

CUDA 11.5 , cuDNN v8.2.1 (June 7th, 2021), for CUDA 11.x

GPU
Max FPS: 14
Avg FPS: 9,09
Min FPS: 0

CPU
Max FPS: 12
Avg FPS: 9,25
Min FPS: 3

CUDA 11.3 , cuDNN v8.2.1 (June 7th, 2021), for CUDA 11.x

GPU
Max FPS: 15
Avg FPS: 12,08
Min FPS: 1

CPU
Max FPS: 10
Avg FPS: 9,1
Min FPS: 3

@AlexSim  what are your PC stats ?

**Comment by kkarahainko** [comment]
@AndersEben can you try latest Nuget pkg or clone latest repo, some optimizations were added few days ago, maybe you use older version, have no other ideas )

**Comment by kkarahainko** [comment]
@AndersEben Debug and Release builds show different performance, keep in mind.

**Comment by AndersEben** [comment]
@kkarahainko 
Yes you are right in release build results are :

CUDA 11.3 , cuDNN v8.2.1 (June 7th, 2021), for CUDA 11.x

CPU
Max FPS: 20
Avg FPS: 16,4
Min FPS: 9

GPU
Max FPS: 32
Avg FPS: 23,415
Min FPS: 1

I will rebuild my other project and try out and show results here first test was slow as well by size 1280
