### ISSUE TITLE
Cannot make custom model work

### ISSUE THREAD

**Issue by fpalsson** [mentalstack/yolov5-net#33]
I have trained a model based on yolov5s6 and exported to onnx. Detection works in detect.py, but I'm not able to get predictions in yolov5-net. I guess I have implemented the custom model incorrectly. Honestly I don't know where to find the correct values to use (have looked in netron, but to no avail).

Linkning the trained model, implementation below. Hope you can give feedback on how to make this work. And how to make it work with future models as well. Perhaps I might suggest an FAQ entry for this, or some details/suggestions in the source for those just getting started?

https://drive.google.com/file/d/1umTSaQSA_96_av8rysOI73QE_gSq7GU5/view?usp=sharing

```
        private class YoloSafetyModel : Yolov5Net.Scorer.Models.Abstract.YoloModel
        {
            public YoloSafetyModel()
            {

            }

            public override int Width { get; set; } = 640;
            public override int Height { get; set; } = 640;
            public override int Depth { get; set; } = 3;

            public override int Dimensions { get; set; } = 85;

            public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

            public override float[][][] Anchors { get; set; } = new float[][][]
            {
            new float[][] { new float[] { 19, 27 }, new float[] { 44, 40 }, new float[] { 38, 94 } },
            new float[][] { new float[] { 96, 68 }, new float[] { 86, 152 }, new float[] { 180, 137 } },
            new float[][] { new float[] { 140, 301 }, new float[] { 303, 264 }, new float[] { 238, 542 } },
            new float[][] { new float[] { 436, 615 }, new float[] { 739, 380 }, new float[] { 926, 792 } }
            };


            public override int[] Shapes { get; set; } = new int[] { 80, 40, 20 };

            public override float Confidence { get; set; } = 0.20f;
            public override float MulConfidence { get; set; } = 0.25f;
            public override float Overlap { get; set; } = 0.45f;

            public override string[] Outputs { get; set; } = new[] { "output" };

            public override List<Yolov5Net.Scorer.YoloLabel> Labels { get; set; } = new List<Yolov5Net.Scorer.YoloLabel>()
            {
                new Yolov5Net.Scorer.YoloLabel { Id = 1, Name = "class0" },
                new Yolov5Net.Scorer.YoloLabel { Id = 2, Name = "class1" },
                new Yolov5Net.Scorer.YoloLabel { Id = 3, Name = "class2" },
            };

            public override bool UseDetect { get; set; } = true;

        }

```

**Comment by dhunjoshi** [comment]
private class YoloSafetyModel : Yolov5Net.Scorer.Models.Abstract.YoloModel
        {
            public YoloSafetyModel()
            {

            }

            public override int Width { get; set; } = 640;
            public override int Height { get; set; } = 640;
            public override int Depth { get; set; } = 3;

            **public override int Dimensions { get; set; } = 8;**

            public override float[] Strides { get; set; } = new float[] { 8, 16, 32 };

            public override float[][][] Anchors { get; set; } = new float[][][]
            {
            new float[][] { new float[] { 19, 27 }, new float[] { 44, 40 }, new float[] { 38, 94 } },
            new float[][] { new float[] { 96, 68 }, new float[] { 86, 152 }, new float[] { 180, 137 } },
            new float[][] { new float[] { 140, 301 }, new float[] { 303, 264 }, new float[] { 238, 542 } },
            new float[][] { new float[] { 436, 615 }, new float[] { 739, 380 }, new float[] { 926, 792 } }
            };


            **public override int[] Shapes { get; set; } = new int[] { 80, 40, 20, 10 };**

            public override float Confidence { get; set; } = 0.20f;
            public override float MulConfidence { get; set; } = 0.25f;
            public override float Overlap { get; set; } = 0.45f;

            public override string[] Outputs { get; set; } = new[] { "output" };

            public override List<Yolov5Net.Scorer.YoloLabel> Labels { get; set; } = new List<Yolov5Net.Scorer.YoloLabel>()
            {
                new Yolov5Net.Scorer.YoloLabel { Id = 1, Name = "class0" },
                new Yolov5Net.Scorer.YoloLabel { Id = 2, Name = "class1" },
                new Yolov5Net.Scorer.YoloLabel { Id = 3, Name = "class2" },
            };

            public override bool UseDetect { get; set; } = true;

        }

**Comment by kkarahainko** [comment]
@fpalsson if you have only 3 classes, change Dimensions to 8, instead of 85.

**Comment by fpalsson** [comment]
Works. You are heros! Thanks!

**Comment by fpalsson** [comment]
Any thoughts about my suggestion to add some info about how to implement the custom model? As a beginner there are so many things to learn...

**Comment by fpalsson** [comment]
I was too quick to say it works. It seems only 2 out of 3 classes are detected. Any clue what could be wrong?

**Comment by kkarahainko** [comment]
@fpalsson can you provide a test image?

**Comment by fpalsson** [comment]
> @fpalsson can you provide a test image?

https://drive.google.com/file/d/1zeVGRX759usnGRPfwcdj9wyzlu2aPdCr/view?usp=sharing

Thanks in advance.

**Comment by kkarahainko** [comment]
![result](https://user-images.githubusercontent.com/1279307/138589862-aa6f6af8-82e6-4ace-a019-ad76ac3ef9dc.jpg)

**Comment by kkarahainko** [comment]
@fpalsson looks like everything works fine.

```
public class SafetyModel : YoloModel
    {
        public override int Width { get; set; } = 640;
        public override int Height { get; set; } = 640;
        public override int Depth { get; set; } = 3;

        public override int Dimensions { get; set; } = 8;

        public override int[] Strides { get; set; } = new int[] { 8, 16, 32, 64 };

        public override int[][][] Anchors { get; set; } = new int[][][]
        {
            new int[][] { new int[] { 009, 011 }, new int[] { 021, 019 }, new int[] { 017, 041 } },
            new int[][] { new int[] { 043, 032 }, new int[] { 039, 070 }, new int[] { 086, 064 } },
            new int[][] { new int[] { 065, 131 }, new int[] { 134, 130 }, new int[] { 120, 265 } },
            new int[][] { new int[] { 282, 180 }, new int[] { 247, 354 }, new int[] { 512, 387 } }
        };

        public override int[] Shapes { get; set; } = new int[] { 80, 40, 20, 10 };

        public override float Confidence { get; set; } = 0.20f;
        public override float MulConfidence { get; set; } = 0.25f;
        public override float Overlap { get; set; } = 0.45f;

        public override string[] Outputs { get; set; } = new[] { "output" };

        public override List<YoloLabel> Labels { get; set; } = new List<YoloLabel>()
        {
            new YoloLabel { Id = 1, Name = "class-1" },
            new YoloLabel { Id = 2, Name = "class-2" },
            new YoloLabel { Id = 3, Name = "class-3" }
        };

        public override bool UseDetect { get; set; } = true;

        public SafetyModel()
        {

        }
    }
```

and usage

```
using var image = Image.FromFile("Assets/test.jpg");

using var scorer = new YoloScorer<SafetyModel>("Assets/Weights/best.onnx");

List<YoloPrediction> predictions = scorer.Predict(image);
```

**Comment by fpalsson** [comment]
Thanks!

My anchors and strides were different as well. Using your model worked fine.

I notice that you have ints for anchors and strides. In my package those are floats. How come that differs?

Followup question: how do you calculate dimensions based on the number of classes?

I guess the order of the classes in the labels list is the mapping to to the classes? Is there any way to map the labels in the list to the class names, to avoid risk of mixing things up if the model is updated and the order of the classes changed?

**Comment by kkarahainko** [comment]
1. Clone the latest repo version to use ints, or you can still use floats.
2. 5 + number of classes.
3. Labels, classes should go as they go while training, nothing to do here.

**Comment by fpalsson** [comment]
Again, thanks!

**Comment by kkarahainko** [comment]
@fpalsson thanks for input, I'll publish a new version of NuGet package, with all recent changes later.
