### ISSUE TITLE
Feature suggestion: Simplify custom model usage

### ISSUE THREAD

**Issue by fpalsson** [mentalstack/yolov5-net#34]
I do not know if this is possible, but I will give it a shot.

When using custom models in detect.py, there is no need to specify all the details that need to go into an overridden Yolov5Net.Scorer.Models.Abstract.YoloModel. The inference works without the details and that leads me to thnk that it is possible to find all information needed from the model and/or information about image dimesion. 

Would it be possible to implement a Yolov5Net.Scorer.Models.YoloCocoP5ModelAuto (or P6) that takes a minimum amount of initialization data such as width, height, confidence (and possibly a list of class name mappings)? It would be very helpful!

**Comment by kkarahainko** [comment]
@fpalsson python version is also stores model configs in files, look at models folder, anyway I'll think about your request.
