### ISSUE TITLE
The Speed is too slow.

### ISSUE THREAD

**Issue by MrXin95** [mentalstack/yolov5-net#35]
Now I want to deploy the Yolo.onnx model in the c# application. I used your code to test. It takes 30 seconds to predict 100 images using yolov5s.onnx (my CPU is i5-1135g7). On the same computer, it uses the same model and onnxruntime acceleration. It takes only 6 seconds in Python language to predict 100 images? What caused the loss of speed? How to optimize？

**Comment by kkarahainko** [comment]
Version of yolov5-net package? Debug or Release build?

**Comment by kkarahainko** [comment]
@MrXin95 try out the latest version of Nuget package, build this CPU bench in Release:

```
var sw = new Stopwatch();
using var image = Image.FromFile("Assets/test.jpg");
using var scorer = new YoloScorer<YoloCocoP5Model>("Assets/Weights/yolov5s.onnx");
List<long> stats = new List<long>();

for (int i = 0; i < 100; i++)
{
    sw.Restart();
    scorer.Predict(image);
    long fps = 1000 / sw.ElapsedMilliseconds;
    stats.Add(fps);
    Console.WriteLine($"FPS: {fps}");
    sw.Stop();
}

Console.WriteLine($"Max FPS: {stats.Max()}");
Console.WriteLine($"Avg FPS: {stats.Average()}");
Console.WriteLine($"Min FPS: {stats.Min()}");

Console.ReadKey();
```

Run and provide your stats here.

**Comment by kkarahainko** [comment]
@MrXin95 pls also provide test image.

**Comment by MrXin95** [comment]
It seems that the version I installed is 1.0.7, but I can't update to 1.0.9. I don't know why
![image](https://user-images.githubusercontent.com/43596264/139405930-afcdf753-4a8c-4fc4-a9ed-9088aa3320f8.png)

![image](https://user-images.githubusercontent.com/43596264/139402929-15198f98-5009-4f78-a302-f8ab5e085c5d.png)
The FPS shown here seems to be faster than I tested. Is it slow for me to traverse the data? But it is still slower than Python;
```C#

            Stopwatch sw = new Stopwatch();
            sw.Start();

            string img_path = "Assets/Imgs";
            DirectoryInfo root = new DirectoryInfo(img_path);
            foreach (FileInfo f in root.GetFiles())
            {
                string img_root = f.FullName;
                string img_name = f.Name;

                using var image = Image.FromFile(img_root);
                using var scorer = new YoloScorer<YoloCocoP5Model>("Assets/Weights/yolov5s.onnx");

                List<YoloPrediction> predictions = scorer.Predict(image);

                using var graphics = Graphics.FromImage(image);

                foreach (var prediction in predictions) // iterate predictions to draw results
                {
                    double score = Math.Round(prediction.Score, 2);

                    graphics.DrawRectangles(new Pen(prediction.Label.Color, 1),
                        new[] { prediction.Rectangle });

                    var (x, y) = (prediction.Rectangle.X - 3, prediction.Rectangle.Y - 23);

                    graphics.DrawString($"{prediction.Label.Name} ({score})",
                        new Font("Consolas", 16, GraphicsUnit.Pixel), new SolidBrush(prediction.Label.Color),
                        new PointF(x, y));
                }

                image.Save("Assets/Results/" + img_name);


            }
            sw.Stop();

            Console.WriteLine(sw.Elapsed);

```
I also tested whether c# drawing frames and saving pictures are slow. After I removed that step, testing 100 images is 28 seconds, but Python only takes 5 seconds.

**Comment by kkarahainko** [comment]
@MrXin95 why can't you update to 1.0.9. what error message?

**Comment by kkarahainko** [comment]
@MrXin95 can you provide test image, python benchmark code as well, and python output to be sure it doesnt use GPU.

**Comment by AndersEben** [comment]
@MrXin95 
You have to define the YoloScorer outside the loop else it will load for every File new, what will cause the low speed


            Stopwatch sw = new Stopwatch();
            sw.Start();

            string img_path = "Assets/Imgs";
            DirectoryInfo root = new DirectoryInfo(img_path);

            // ----
            using var scorer = new YoloScorer<YoloCocoP5Model>("Assets/Weights/yolov5s.onnx");
            // ----

            foreach (FileInfo f in root.GetFiles())
            {
                string img_root = f.FullName;
                string img_name = f.Name;

                using var image = Image.FromFile(img_root);
                
                List<YoloPrediction> predictions = scorer.Predict(image);

                using var graphics = Graphics.FromImage(image);

                foreach (var prediction in predictions) // iterate predictions to draw results
                {
                    double score = Math.Round(prediction.Score, 2);

                    graphics.DrawRectangles(new Pen(prediction.Label.Color, 1),
                        new[] { prediction.Rectangle });

                    var (x, y) = (prediction.Rectangle.X - 3, prediction.Rectangle.Y - 23);

                    graphics.DrawString($"{prediction.Label.Name} ({score})",
                        new Font("Consolas", 16, GraphicsUnit.Pixel), new SolidBrush(prediction.Label.Color),
                        new PointF(x, y));
                }

                image.Save("Assets/Results/" + img_name);


            }
            sw.Stop();

            Console.WriteLine(sw.Elapsed);

**Comment by kkarahainko** [comment]
@AndersEben ah, you're right, didn't notice that.
