### ISSUE TITLE
Unreliable predictions

### ISSUE THREAD

**Issue by fpalsson** [mentalstack/yolov5-net#36]
When doing further tests, I realize that quite often I get strange results. 

I have exported a PyTorch model to ONNX using Yolov5 export.py.

I have compared inference using:
* detect.py with the original pytorch model
* detect.py with the pytorch model exported to onnx
* running yolov5net with a custom model using the exported onnx

The scores are varying sligtly between the .pt and .onnx when running in PyTorch, but it is stable.

But when running the onnx model in yolov5net often predictions are not even there. Consider the results below.

Original image:

![](https://drive.google.com/uc?id=1qy5-VbiNQhQPsGh6imCPpCwu8EFIQogC)

Detect.py with the original pytorch model:

![](https://drive.google.com/uc?id=1sivnbwIrQ3oaVbRjrzgL0x3QMsvw64Xu)

detect.py with the pytorch model exported to onnx:

![](https://drive.google.com/uc?id=1Pm3ouiniIavFsnfrVMNPsfDoLaqzSExJ)

running yolov5net with a custom model using the exported onnx (noice the missing person prediction):

![](https://drive.google.com/uc?id=1aC9SXax6mwwckWfB8aWU2hMk1_Xim98A)

The custom model is here: https://drive.google.com/file/d/1nuGc2aQMIvniWxvwkwPpvn-Cf2PaJF98/view?usp=sharing

The implementation of the model class is like this:

```
 private class YoloSafetyModel : Yolov5Net.Scorer.Models.Abstract.YoloModel
        {
            public override int Width { get; set; } = 640;
            public override int Height { get; set; } = 640;
            public override int Depth { get; set; } = 3;

            public override int Dimensions { get; set; } = 9;  //5 + num_classes

            public override float[] Strides { get; set; } = new float[] { 8, 16, 32, 64 };

            public override float[][][] Anchors { get; set; } = new float[][][]
            {
                new float[][] { new float[] { 009, 011 }, new float[] { 021, 019 }, new float[] { 017, 041 } },
                new float[][] { new float[] { 043, 032 }, new float[] { 039, 070 }, new float[] { 086, 064 } },
                new float[][] { new float[] { 065, 131 }, new float[] { 134, 130 }, new float[] { 120, 265 } },
                new float[][] { new float[] { 282, 180 }, new float[] { 247, 354 }, new float[] { 512, 387 } }
            };

            public override int[] Shapes { get; set; } = new int[] { 80, 40, 20, 10 };

            public override float Confidence { get; set; } = 0.20f;
            public override float MulConfidence { get; set; } = 0.25f;
            public override float Overlap { get; set; } = 0.45f;

            public override string[] Outputs { get; set; } = new[] { "output" };

            public override List<Yolov5Net.Scorer.YoloLabel> Labels { get; set; } = new List<Yolov5Net.Scorer.YoloLabel>()
            {
                new Yolov5Net.Scorer.YoloLabel { Id = 1, Name = "helmet" },
                new Yolov5Net.Scorer.YoloLabel { Id = 2, Name = "logotype" },
                new Yolov5Net.Scorer.YoloLabel { Id = 3, Name = "person" },
                new Yolov5Net.Scorer.YoloLabel { Id = 4, Name = "safety_west" }
            };

            public override bool UseDetect { get; set; } = true;

            public YoloSafetyModel()
            {

            } 
     }
```

**Comment by kkarahainko** [comment]
@fpalsson change overlap to 0.50 for example.

**Comment by fpalsson** [comment]
> @fpalsson change overlap to 0.50 for example.

As simple as that. Thanks!

So Overlap filters out everything with a larger overlap than set (intersection area divided by union area). Correct? This means the west will filter out the person. Is there any rules what object stays, and what gets filtered out? Based on order of classes in the model?

MulConfidence, then? Would you care to elaborate on that a little?

**Comment by kkarahainko** [comment]
@fpalsson nms now super simple, class agnostic - object with higer score wins

```
if (overlap > _model.Overlap)
{
    if (item.Score > current.Score)
    {
        result.Remove(current);
    }
}
```

**Comment by kkarahainko** [comment]
@fpalsson if you need nms filter only the same class objects, its possible to add another condition like 

```
if (item.Score > current.Score && item.Label == current.Label)
{
    result.Remove(current);
}
```

but you may get redundant predictions - the same object multiple predictions, classes.

**Comment by fpalsson** [comment]
@kkarahainko: Thanks for these snippets. I guess you mean that if I would set the overlap to 1.0 and thereby disable the filtering in yolov5net I could implement these algoritms myself. Or did you mean something else?

**Comment by kkarahainko** [comment]
@fpalsson the same overlap, no need to set it to 1.0, but only the same class, so person wont be filtered by bus etc, or helmet in your case. If you'll call detect.py with --agnostic param then person will be filtered too, as well as in yolov5net

**Comment by fpalsson** [comment]
@kkarahainko I might be stupid but need to ask a followup question:

How do I in yolv5net replicate the behaviour of detect.py when NOT using --agnostic param?

**Comment by kkarahainko** [comment]
@fpalsson no worries, look at the Supress method in YoloScorer.cs, you will find:

```
if (overlap > _model.Overlap)
{
    if (item.Score > current.Score ** && item.Label == current.Label **)
    {
        result.Remove(current);
    }
}
```
** condition will add class-awareness, if you need this asap you may clone and add this changes yourself, this is open-source project, maybe I will add new property to model config for this later.

**Comment by fpalsson** [comment]
Aha, you were referencing a change in the repo. Didn't get that. Thanks.

**Comment by SUNbrightness** [comment]
> 

Newbie thanks
//5 + num_classes This note helped me solve my puzzle
