### ISSUE TITLE
optional detect layer parsing added 

### ISSUE THREAD

**Issue by xu998** [mentalstack/yolov5-net#4]
hi,
I get the onnx from
python export.py --weights yolov5s.pt --img 640 --batch 1
it outputs do not have 561
what can I do add it ?

**Comment by kkarahainko** [comment]
@xu998 hi, check outputs with Netron https://i.imgur.com/qmiEU4Y.png, https://netron.app

**Comment by kkarahainko** [comment]
if no detect layer exported, set UseDetect = false, OutputNames = new[] { output1, output2, output3 }
