### ISSUE TITLE
not detecting anything

### ISSUE THREAD

**Issue by MasIgor** [mentalstack/yolov5-net#48]
Hello, I am completely new on this topic so please excuse if I did something wrong.

I trained my network in colab, and got my best.pt file. The i use this to convert it to a onnx file:

`
!python /content/yolov5/export.py --weights /content/yolov5/runs/train/exp/weights/best.pt --data /content/datasets/SL-CratesBig-2/data.yaml --include onnx 
`

I took one of the test images taht was proeprly recognized with a confidence of 0.98 and saved it in my project folder with the name test.jpg.

below is my code.

Predictions has always count 0.  
any idea why?

thank you!

```
Imports Yolov5Net

Public Class Form1
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim image As Image
        image = Image.FromFile("Assets/test.jpg")

        Dim myscorer As New Yolov5Net.Scorer.YoloScorer(Of Yolov5Net.Scorer.Models.YoloCocoP5Model)("Assets/Weights/best.onnx")


        Dim predictions As List(Of Scorer.YoloPrediction) = myscorer.Predict(image)

        Dim g As Graphics = Graphics.FromImage(image)
        For Each prediction In predictions
            Dim score As Double = Math.Round(prediction.Score, 2)


            g.DrawRectangles(New Pen(prediction.Label.Color, 1), New RectangleF() {prediction.Rectangle})
            Dim x As Integer = prediction.Rectangle.X - 3
            Dim y As Integer = prediction.Rectangle.Y - 23


            g.DrawString("{prediction.Label.Name} ({score})", New Font("Arial", 16, GraphicsUnit.Pixel), New SolidBrush(prediction.Label.Color), New PointF(x, y))
        Next
        image.Save("Assets/result.jpg")
    End Sub
End Class
```

**Comment by gillonba** [comment]
A) Did you run predict.py on the image with your ONNX model?

B) Did you change the category list in your model and if so did you change it in your scorer as well?

**Comment by MasIgor** [comment]
thank you for your answer gillonba, please bear with me, as i am only partially understanding your questions.

A) there is no predict.py in my yolo v5 folder. if you mean the detect.py then yes, i did and it works. here is a screenshot:
![image](https://user-images.githubusercontent.com/67956327/154024318-8d374292-02ff-4fa5-bccf-0a81d9d280ca.png)

B) How do I do that? how can the category list be changed? isnt that done automatically when converting?

**Comment by MasIgor** [comment]
I uploaded the c#.net project to my ftp, with the onnx model, one test image and the data.yaml file.

www.igormasin.it/fileuploads/test.zip

**Comment by gillonba** [comment]
A) If I remember correctly, detect.py should output an image with detections drawn onto it.  Do the detections appear to be correct?

B) If you are using a custom dataset with labels different than the default COCO dataset, you will have to update the Labels list in YoloCocoP5Model.cs to match the labels you trained with

**Comment by MasIgor** [comment]
A) yep, it is detected properly and drawn on the image.

B) thank you, I'm not able to find this file in my project. any idea of where it is located?

**Comment by MasIgor** [comment]
I managed to solve it by crating a new class, copying in the existing models found online, and editing them. thank you very much for your help gillonba!

**Comment by masgh21** [comment]
@gillonba 
Hello Can you help me with this problem ?
[Error](https://github.com/mentalstack/yolov5-net/issues/57)
