### ISSUE TITLE
It does not work with custom onnx 

### ISSUE THREAD

**Issue by StefanCiobanu1989** [mentalstack/yolov5-net#5]
Hi, i know i'm doing something wrong but i cant tell what it is .
When i run the code i get the following error : 
![image](https://user-images.githubusercontent.com/86718588/128246087-cf8beff6-a5d5-4539-a6e2-dbdd59af5b84.png)

This is the model config and i think here is where i'm missing something : 
![image](https://user-images.githubusercontent.com/86718588/128246244-23ab5068-75bd-4fd3-a0e2-85920e551fc9.png)
i have no idea what "Dimensions", "Anchors", "Shapes" do or mean but i think this is what's preventing me from successfully running. Some help would be amazing. Thank you

**Comment by kkarahainko** [comment]
@StefanCiobanu1989 hi, can you inspect your model with https://netron.app/, I need this https://i.imgur.com/OMPx26W.png, or send me your onnx file.

**Comment by StefanCiobanu1989** [comment]
> @StefanCiobanu1989 hi, can you inspect your model with https://netron.app/, I need this https://i.imgur.com/OMPx26W.png, or send me your onnx file.

![image](https://user-images.githubusercontent.com/86718588/128321193-5b209a28-4972-4529-b0d3-c8a91ec543f2.png)

**Comment by kkarahainko** [comment]
@StefanCiobanu1989 change Dimensions parameter to 6 instead of 85.

**Comment by StefanCiobanu1989** [comment]
> @StefanCiobanu1989 change Dimensions parameter to 6 instead of 85.

I have changed it to it still says "'Index was outside the bounds of the array.'".

**Comment by kkarahainko** [comment]
@StefanCiobanu1989 looks like output name is also wrong, please change OutputNames to { "output" } instead of { "519" } because you use detect layer.

**Comment by StefanCiobanu1989** [comment]
> @StefanCiobanu1989 looks like output name is also wrong, please change OutputNames to { "output" } instead of { "519" } because you use detect layer.

My friend... you are a god ! That did it i can now use my custom model!! Spasiba very much for your assistance! 

I have a request if possible. Could you make a video guide or text about how to tell where to pick the values we went trough? 
I mean what if i was to create a new custom model how would i adapt my code to match it ? 

Thank a lot again !

**Comment by kkarahainko** [comment]
@StefanCiobanu1989 thanks man, you're welcome, all you need is Netron, and these params https://i.imgur.com/EYJa3VE.png.

**Comment by kkarahainko** [comment]
@StefanCiobanu1989 you can also calc dimensions as "5 (fixed layers for bboxes conf etc) + number of your labels", you have 1 label so your dimensions is 6, if you'll have 3 custom labels it will be 8 so on.

**Comment by StefanCiobanu1989** [comment]
> @StefanCiobanu1989 you can also calc Dimensions as "5 (fixed layers for bboxes conf etc) + number of your labels", you have 1 label so your Dimensions is 6, if you'll have 3 custom labels it will be 8 so on.

Much appreciated
