### ISSUE TITLE
It's me again !

### ISSUE THREAD

**Issue by StefanCiobanu1989** [mentalstack/yolov5-net#6]
Hi again,
This time i'm not coming back with an issue it more of a question to which i could not find the answer.
I have not managed to implement GPU usage instead of CPU i downloaded the onnx runtime gpu and still cant get it to work.
Have you done any experiments of this sort in the past ? Have you got it to work with videos ? Thanks !

**Comment by kkarahainko** [comment]
@StefanCiobanu1989 sorry, didn't try it.
