### ISSUE TITLE
my custom model.onnx work perfectly in detect.py but not in yolov5-net

### ISSUE THREAD

**Issue by tracywong117** [mentalstack/yolov5-net#62]
MacOS 10.15
Visual Studio for Mac 17.0.3

I have tried image and model (yolov5s.onnx) in the depository. 

This is the image.
![trial](https://user-images.githubusercontent.com/25502528/175190309-0ecc8a47-480f-4726-84a9-23986ab835c5.jpg)

And, I get the result.
![result](https://user-images.githubusercontent.com/25502528/175190318-4ae4b07a-302c-4906-9193-7388e7c79c99.jpg)
So, I think I have set up things correctly in Visual Studio.

My custom model.onnx work perfectly with detect.py after converting from .pt to .onnx.

When I use yolov5-net and laod my custom model.onnx, I can load the model.onnx too and it gives the result. But the result is not the same as detect.py. It just can't detect anything.

Result I get from detect.py:
![trial1](https://user-images.githubusercontent.com/25502528/175190819-a179cf23-76a1-4c67-9a73-36d63028ac2c.jpg)

Result I get from yolov5-net
![result1](https://user-images.githubusercontent.com/25502528/175190775-95978e21-0f72-4edc-abd1-a7b11ee50e24.jpg)

I have tried more examples but it still  can't detect anything with yolov5-net.

May you help me to solve the problem?  I need to deploy my model in C#. 

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/25502528/175191863-5cd37dde-3e49-43f4-b39d-a59612dc8411.png">

Thank you! 🙏 

.

**Comment by ducpm151061** [comment]
#48

**Comment by tracywong117** [comment]
Thanks!!

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/25502528/175206687-ed1d49b2-dbde-43c4-b31c-821fc1b93af0.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/25502528/175207071-abd2bb2e-6866-4bc2-9875-2fc5610150c2.png">

I think I have inherited from YoloModel and overridden all the required properties and methods. Am I doing it correctly? 
My custom model still can't detect anything.

classes:
0: face 
1: mobile
2: camera
3: laptop
4: tablet

**Comment by ducpm151061** [comment]
> Thanks!!
> 
> <img alt="image" width="1429" src="https://user-images.githubusercontent.com/25502528/175206687-ed1d49b2-dbde-43c4-b31c-821fc1b93af0.png">
> 
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/25502528/175207071-abd2bb2e-6866-4bc2-9875-2fc5610150c2.png">
> 
> I think I have inherited from YoloModel and overridden all the required properties and methods. Am I doing it correctly? My custom model still can't detect anything.
> 
> classes: 0: face 1: mobile 2: camera 3: laptop 4: tablet

Dimensions=10

**Comment by tracywong117** [comment]
It works!!!! Thank you so much. ☺️ 
May I know what is dimension? And how it is calculated? 
THANK YOU!!!

**Comment by tracywong117** [comment]
I understand now. Because the output dimension is num_class + 4 (x1, y1, x2, y2 coordinates) + 1 (confidence score).
