### ISSUE TITLE
Help with using Yolov5l.onnx

### ISSUE THREAD

**Issue by Nisse123** [mentalstack/yolov5-net#7]
First, thank you for posting this code.
I am trying to use another Yolov5 model but I do not understand what to change.
In Netron, the model has 3 outputs (screen shoot). 
I changed UseDetect to false and Outputnames to { "out0", "out1", "out2" }; but the result is garbage
I do not understand the relation between all the parameters here, could you please point out what needs to be changed?

I notice in Netron that there are different yolov5s.onnx models. The one you have has a detection layer but other only have the outputs, how come?

Thanks,

![image](https://user-images.githubusercontent.com/74415584/129210004-b894acb7-3667-4cad-adb1-df43711341da.png)

![image](https://user-images.githubusercontent.com/74415584/129210368-6cad01e8-4b7b-4138-8195-ec6a51d63f19.png)

**Comment by kkarahainko** [comment]
@Nisse123 hi, did you export the default yolov5l (with coco dataset) model or it's something custom trained?

**Comment by kkarahainko** [comment]
@Nisse123 outputs should look like https://i.imgur.com/iEMv3A7.png, maybe you have an older version, outputs look strange, try export with the latest yolov5 release https://github.com/ultralytics/yolov5.

**Comment by kkarahainko** [comment]
@Nisse123 just exported the latest yolov5l.pt to onnx, works good https://drive.google.com/file/d/1HwqT_P_svYux6J1z-FXAVXWlq-C4PlPR/view, pls try.

**Comment by Nisse123** [comment]
Thank you!
I must have picked a bad model, my mistake.

Would you like to point out what need to be changed if I want to test the higher resolution models like YOLOv5m6?
Is it to change Width and Height to 1280 or do I need to change more parameters?

If I want to learn the specification for output,651, 712,773 , the meaning of the order of the parameters, could you please point out some tutorial or something. I have really tried to google it and it seems only be documented  by convention in different python code libraries.

Thanks again for the help.

![image](https://user-images.githubusercontent.com/74415584/129317324-6d498fc9-2106-4b40-99bb-6defd7171fca.png)

**Comment by kkarahainko** [comment]
@Nisse123 I've just added P6 example, take a look, I don't think I'll have enough time and knowledge to write yolov5 paper ;) it'll be better to wait for the official paper, docs from the author. Anyway, yolo5 docs and code are quite clear, you may find anchors (for example) here https://github.com/ultralytics/yolov5/blob/master/models/hub/anchors.yaml, shapes, and all other parameters are available in Netron, so try and experiment.

**Comment by kkarahainko** [comment]
@Nisse123 to try P6 just change the model type here https://i.imgur.com/pWhUTaM.png to YoloCocoP6Model.
