### ISSUE TITLE
Unable to find an entry point named ‘OrtGetApiBase’ in DLL ‘onnxruntime’ 

### ISSUE THREAD

**Issue by cross-hello** [mentalstack/yolov5-net#9]
I am sorry that VS2019 give me such a reponse when I finally locate it in here:
![image](https://user-images.githubusercontent.com/42733664/130216030-6a026431-e469-448e-870a-2d12ddcd375a.png)
Could you help me anyway?

**Comment by cross-hello** [comment]
I am using .Net framework 4.7.2, and I installed it from NuGet Package Manager with **Microsoft.ML.OnnxRuntime** 1.8.1

**Comment by kkarahainko** [comment]
@cross-hello can't reproduce, just created 4.7.2 Console App (https://i.imgur.com/dnD6VLn.png). Installed the Yolov5Net 1.0.2 package from Nuget (check latest version https://www.nuget.org/packages/Yolov5Net/1.0.2), and It works. No need to install OnnxRuntime it comes with Yolov5Net package.

**Comment by kkarahainko** [comment]
@cross-hello try to debug this https://drive.google.com/file/d/1k_I7gekUdWqnZoluBkwyohVi0i8K_kHk/view

**Comment by kkarahainko** [comment]
@cross-hello ok, after restoring packages it doesnt copy onnxruntime.dll look at this https://github.com/microsoft/onnxruntime/issues/1699 it's known issue, you may copy always dll from packages folder (...\packages\Microsoft.ML.OnnxRuntime.1.8.1\runtimes\win-x86) or specify platform (x64, x86) as described.

**Comment by cross-hello** [comment]
Thanks for your reply, it is sorry that I may no some familar with C sharp platform. It is still a time for us= - =
Thank you
